#############################
#        TO FILL            #
#############################

# The title that appears on the tab
title: Veronica's Gallery

# The title on the web page
full_name: Veronica Tan Xiang Yu

# The type of layout
# Options: ROWS, SQUARES, COLUMNS
layout_style: ROWS

# Integer: Spacing between each photo
spacing: 10

# Boolean(true|false): Shuffle the photos in the album
shuffle: false

# Integer: Number of columns for square or columns
columns: 4

# Integer: Max height for rows
max_height: 400

# Handle
instagram: veronica_txy

######################
# END OF CONFIG CODE #
#  Ignore below :)   #
######################
#
# Name of your gallery (this will show up at the top of your page and in the RSS feed)
name: Gallery

# Short description (goes below the title; it will also be used in the RSS feed)
description: My Photography Portfolio

# Your self-description paragraph
self_description: >
  Photography is how I make sense of the world—
  the intricate beauty in every detail, the composition of objects, the combinations of color, and the play of light. 
  I’ve learned to appreciate the world even more deeply through my lens, and I hope my photos bring you the same comfort they bring me.

# Your name, as you want it to appear underneath each post and in the footer
author: Veronica Tan

# Your email if you want it to be linked on the contact page
author_email: qwerty_vtan@hotmail.com

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
baseurl: /

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
# url: http://github.com/veronicatanxiangyu/Veronica-Gallery/